### ISSUE TITLE
Convert sigma v1 tag format to v2 format

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/sigma-to-hayabusa-converter#17]
Unfortunately, the format for the MITRE ATT&CK tags for deprecated and unsupported rules did not get updated to the v2 format so during rule conversion let's update the v1 tags to v2 so they are properly handled by Hayabusa.

Example: `initial_access` -> `initial-access`

**Comment by fukusuket** [comment]
https://github.com/Yamato-Security/hayabusa/pull/1395

**Comment by YamatoSecurity** [comment]
We should probably updated the underscores to hyphens for CVE and detection tags as well. Not just MITRE: https://github.com/SigmaHQ/sigma-specification/blob/main/other/version-2-changes.md
