### ISSUE TITLE
Temporarily convert `|fieldref` to `|equalsfield`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/sigma-to-hayabusa-converter#24]
Right now there is only one rule that uses the `fieldref` modifier but I think they will increase in the future.
Hayabusa will support it natively in the next release at SecTor but it will take some time before people update to the latest version. So in order to use sigma rules that use `|fieldref`, I think we can just change the modifier to `|equalsfield` when converting which does the same thing and Hayabusa already supports. Then some time in December we can stop renaming the field and support `fieldref` rules natively. 
@fukusuket What do you think?

**Comment by fukusuket** [comment]
Sounds good! I'll implement it💪
