### ISSUE TITLE
refactoring `logsource_mapping.py` and adding unit test

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/sigma-to-hayabusa-converter#4]
The `logsource_mapping.py` code is getting complicated and it is difficult to add functionality... so I will refactor it and add more unit tests.

**Comment by YamatoSecurity** [comment]
@fukusuket Is it ok to close this or did you want to refactor more?

**Comment by fukusuket** [comment]
@YamatoSecurity  
Yes, it is OK to close! (More refactoring would be better...😅, but I'll deal with that when I have time)
